### ISSUE TITLE
bitbake meta-toolchainがエラーになります

### ISSUE THREAD

**Issue by hanada1188** [ubinux/dnf-plugin-tui#3]

**Comment by hanada1188** [comment]
花田と申します。

Ubuntu 20.04環境でubinux環境を構築しているのですが、dnf-plugin-tuiでmakeが通らず困っております。
アドバイス頂けないでしょうか？

Yocto-ubinuxに関してはgithubのページを参考に
$ bitbake ubinux-allが全て問題なく終了しました。
その後、dnf-plugin-tuiのgithubのページを参考に
$ bitbake meta-toolchain
を実行したのですが、以下のようにエラーになっており、
何が不足しているのかアドバイス頂けないでしょうか。

~/build$ bitbake meta-toolchain
WARNING: Host distribution "ubuntu-20.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |################################################################| Time: 0:00:00 Loaded 1301 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'nativesdk-dnf-plugin-tui'
NOTE: Runtime target 'nativesdk-dnf-plugin-tui' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nativesdk-dnf-plugin-tui']
ERROR: Required build target 'meta-toolchain' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-toolchain', 'nativesdk-dnf-plugin-tui']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

ちなみに、conf/local.confに何も追加していない状態（デフォルト状態）とnativesdk-createrepo-cのみ追加した状態では
以下のようにエラーにはなっておりません。
~/build $ bitbake meta-toolchain
WARNING: Host distribution "ubuntu-20.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |################################################################| Time: 0:00:00 Loaded 1301 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "x86_64-poky-linux"
MACHINE              = "qemux86-64"
DISTRO               = "poky"
DISTRO_VERSION       = "3.0.4"
TUNE_FEATURES        = "m64 core2"
TARGET_FPU           = ""
meta
meta-poky
meta-yocto-bsp       = "zeus:d88d62c20d7d8da85f02edb170dae0280624ad7e"

Initialising tasks: 100% |###########################################################| Time: 0:00:01 Sstate summary: Wanted 0 Found 0 Missed 0 Current 1308 (0% match, 100% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
NOTE: Tasks Summary: Attempted 3677 tasks of which 3677 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.

初歩的な質問で申し訳ありませんが、よろしくお願いいたします。

**Comment by zhengrq-fnst** [comment]
提供していただいたログから見ると、花田さんはYocto-ubinuxに対する必要なlayerを全部ダウンロードしていないと推測します。

そして、理由を説明します。
先ず、dnf-plugin-tuiのレシピ ファイルはmeta-openembeddedというlayerに置いてあります。
bitbakeのログによって、dnf-plugin-tuiのレシピ ファイルが見つかりません。
それに、花田さんのディレクトリに、meta-oeがありません。

```
TARGET_FPU = ""
meta
meta-poky
meta-yocto-bsp = "zeus:d88d62c20d7d8da85f02edb170dae0280624ad7e"
Initialising tasks: 100......
```

なので、https://github.com/ubinux/yocto-ubinuxのセクション 3.1の手順によって、実施しましたか？

もし、実施したら、正常に動作できましたか？

```
3.1 Download repos 
$ cd yocto-ubinux/
$ python meta-ubinux/scripts/checkoutmetas.py    ★Ubinuxに対する必要なlayerをダウンロードする
```

**Comment by hanada1188** [comment]
ご返信ありがとうございます。

yocto-ubinuxのセクション3.Usageは全て実施済みで、3.1～3.4まで全て問題なく実施できています。

上記が実施できていれば、
dnf-plugin-tuiの3.1.1 Prepareの(1)toolchainは$ bitbake meta-toolchainまでは
実施不要ということでしょうか？
また、poky-glibc-x86_64-meta-toolchain-core2-64-qemux86-64-toolchain-3.0.shの代わりに
~/ubinux/build-ubinux-x86-64/tmp/deploy/sdk/ubinux-glibc-x86_64-meta-toolchain-core2-64-ubinux-x86-64-toolchain-2021.08.sh
を使用すればいいのでしょうか？

**Comment by zhengrq-fnst** [comment]
もし、yocto-ubinuxのbitbake meta-toolchainの実施が問題なければ、~/ubinux/build-ubinux-x86-64/tmp/deploy/sdk/ubinux-glibc-x86_64-meta-toolchain-core2-64-ubinux-x86-64-toolchain-2021.08.sh
というtoolchainを使用してください。

**Comment by hanada1188** [comment]
ありがとうござます。
yocto-ubinuxのbitbake meta-toolchainは問題なくmakeできていますので、こちらを使ってみます。
